
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyHearthStoneV2.Model
{

using System;
    using System.Collections.Generic;
    
public partial class hs_gamerecord:BaseEntity
{

    public long ID { get; set; }

    public string GameCode { get; set; }

    public string FirstUserCode { get; set; }

    public string SecondUserCode { get; set; }

    public bool IsFirstUserRound { get; set; }

    public string Chessboard { get; set; }

    public int RoundIndex { get; set; }

    public System.DateTime AddTime { get; set; }

}

}
