//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHearthStoneV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_Game :BaseEntity
    {
        public long ID { get; set; }
        public string GameCode { get; set; }
        public string FirstUserCode { get; set; }
        public string SecondUserCode { get; set; }
        public bool IsFirstUserWin { get; set; }
        public System.DateTime AddTime { get; set; }
        public string CurrentRoundCode { get; set; }
        public string NextRoundCode { get; set; }
        public string FirstUserCardGroupCode { get; set; }
        public string SecondUserCardGroupCode { get; set; }
        public string TableCode { get; set; }
    }
}
